### PR TITLE
Get the ReCaptcha language client-side

### PR DESCRIPTION
**Pull request by mrclay**
...Also can get rid of the elgg_define_js in start.php. I did this via the web because laziness.

### CODE REVIEW

**Comment by mrclay** [comment]
Embedding server-side language into elgg_define_js is problematic because that URL gets cached. Particularly, Juho was the last to refresh the cache, so the ReCaptcha lang is set to what he uses (`fi`).

**Comment by beck24** [comment]
Thanks, I'll cleanup the elgg_define_js

**Comment by mrclay** [comment]
I should note, I did not test that :)

**Comment by beck24** [comment]
ok, I'll give it a full once-over
Looks fine at a glance

**Pull request merged**
